---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{ toYaml .Values.deployment.annotations }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  replicas: {{ .Values.deployment.replicas | default 1 }}
  strategy:
    type: {{ .Values.deployment.strategy | default "Recreate" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy | default "IfNotPresent" }}

        {{- if .Values.volumes }}
        volumeMounts:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          mountPath: {{ .path }}
        {{- end }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.deployment.port | default 80 }}
          name: http

        {{- if .Values.deployment.nodeSelector }}
        nodeSelector:
          {{ toYaml .Values.deployment.nodeSelector }}
        {{- end }}

        {{- if or .Values.env .Values.secretRefs }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}

        {{- range .Values.secretRefs }}
        - name: {{ .key }}
          valueFrom:
            secretKeyRef:
              key: {{ .key }}
              name: {{ .name }}
        {{- end }}
        {{- end }}

      {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ $.Values.name }}-{{ .name }}
      {{- end }}
      {{- end }}
