apiVersion: v2
name: paperless-ngx
description: Paperless-ngx is a document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.
version: 0.0.2
appVersion: v2.6.3
dependencies:
- name: template
  alias: paperless
  version: 0.0.3
  repository: https://breuerfelix.github.io/helm-charts
- name: template
  alias: redis
  version: 0.0.3
  repository: https://breuerfelix.github.io/helm-charts
